/* Style reminder: ficha editorial financiera negra y roja, navegación compacta, datos legibles y contenido educativo. */
import { useMemo, useState, type ReactNode } from "react";
import { ArrowLeft, ArrowUpRight, BarChart3, BookOpen, Calculator, CircleDollarSign, ExternalLink, FileText, Play, PieChart, WalletCards } from "lucide-react";
import { getRecommendations } from "@/lib/videoRecommendations";
import { previewVideos } from "@/pages/PreviewEditorial";

type Fiber = { ticker:string; name:string; sector:string; price:string; yield:string; occupancy:string; dividend:string; tone:string; tags:string[]; change?:string; marketCap?:string; pe?:string; annualRange?:string; bookValue?:string; pb?:string; noiMargin?:string; roe?:string; leverage?:string; debtCoverage?:string; properties?:string; ceo?:string; founded?:string; employees?:string; website?:string; address?:string; description?:string; annualDividend?:string; frequency?:string; incomePer100k?:string; adr?:string; revpar?:string; ebitdaMargin?:string; source?:string; lastUpdated?:string };
type Section = "resumen" | "pagos" | "valuacion" | "ocupacion" | "videos" | "reportes";
type Report = { year:number; period:string; label:string; status:"pending"; url?:string };

const data: Record<string, Fiber> = {
  FUNO:{ticker:"FUNO",name:"Fibra Uno",sector:"Diversificado",price:"$29.35",yield:"7.88%",occupancy:"95.4%",dividend:"$2.40",tone:"red",tags:["oficinas","comercio","industrial"]},
  FIBRAPL:{ticker:"FIBRAPL",name:"Fibra Prologis",sector:"Industrial",price:"$74.51",yield:"5.21%",occupancy:"97.0%",dividend:"$4.07",tone:"amber",tags:["industrial","logistica"]},
  FIBRAMQ:{ticker:"FIBRAMQ",name:"Fibra Macquarie",sector:"Industrial",price:"$42.65",yield:"5.43%",occupancy:"96.0%",dividend:"$2.45",tone:"blue",tags:["industrial","logistica"]},
  DANHOS:{ticker:"DANHOS",name:"Fibra Danhos",sector:"Comercial",price:"$28.45",yield:"6.43%",occupancy:"93.5%",dividend:"$1.80",tone:"pink",tags:["comercio","oficinas"]},
  FSHOP:{ticker:"FSHOP",name:"Fibra Shop",sector:"Comercial",price:"$11.95",yield:"—",occupancy:"92.0%",dividend:"$0.67",tone:"green",tags:["comercio","retail"]},
  FINN:{ticker:"FINN",name:"Fibra Inn",sector:"Hotelero",price:"$4.80",yield:"7.48%",occupancy:"68.0%",dividend:"$0.36",tone:"purple",tags:["hoteles","turismo"]},
  FIHO:{ticker:"FIHO",name:"FibraHotel",sector:"Hotelero",price:"$7.54",yield:"7.96%",occupancy:"60.1%",dividend:"$0.60",tone:"teal",tags:["hoteles","turismo"],change:"−$0.12 (−1.57%)",marketCap:"$5,951 M",pe:"17.69x",annualRange:"$6.90 — $8.65",bookValue:"$15.45",pb:"0.52",noiMargin:"13.3%",roe:"39.7%",leverage:"27.2%",debtCoverage:"1.66x",properties:"81 propiedades",ceo:"Simón Galante Zaga",founded:"2012",employees:"29",website:"fibrahotel.com",address:"Torre Corporativo World Plaza",description:"FibraHotel es una FIBRA mexicana enfocada en el sector hotelero, con hoteles de servicio selecto y servicio completo en destinos de negocios y turísticos de México.",annualDividend:"$0.600 por título",frequency:"Trimestral",incomePer100k:"$1,989 por cada $100K",adr:"$1,711",revpar:"$1,029",ebitdaMargin:"23.3%",source:"Datos proporcionados a partir de la ficha pública de FibrasMX y contenido suministrado para esta reconstrucción educativa.",lastUpdated:"Referencia capturada · agosto de 2026"},
  FMTY:{ticker:"FMTY",name:"Fibra Mty",sector:"Diversificado",price:"$14.23",yield:"8.02%",occupancy:"96.0%",dividend:"$0.49",tone:"orange",tags:["industrial","oficinas"]},
  FPLUS:{ticker:"FPLUS",name:"Fibra Plus",sector:"Diversificado",price:"$5.01",yield:"6.85%",occupancy:"93.1%",dividend:"$0.09",tone:"cyan",tags:["comercio","residencial"]},
  NEXT:{ticker:"NEXT",name:"Fibra Next",sector:"Industrial",price:"$2.26",yield:"—",occupancy:"97.7%",dividend:"$2.26",tone:"yellow",tags:["industrial","tecnologia"]},
  FNOVA:{ticker:"FNOVA",name:"Fibra Nova",sector:"Industrial",price:"$41.72",yield:"5.42%",occupancy:"95.0%",dividend:"$2.36",tone:"slate",tags:["industrial","agroindustria"]},
  FHIPO:{ticker:"FHIPO",name:"FHipo Hipotecaria",sector:"Hipotecario",price:"$14.00",yield:"10.04%",occupancy:"—",dividend:"$1.42",tone:"rose",tags:["hipotecario","vivienda"]},
  EDUCA:{ticker:"EDUCA",name:"Fibra Educa",sector:"Educativo",price:"$54.00",yield:"4.69%",occupancy:"98.0%",dividend:"$2.56",tone:"violet",tags:["educativo","escuelas"]},
  STORAGE:{ticker:"STORAGE",name:"Fibra Storage",sector:"Almacenaje",price:"$23.87",yield:"—",occupancy:"83.5%",dividend:"$2.42",tone:"gray",tags:["almacenaje","industrial"]},
  FCFE:{ticker:"FCFE",name:"Fibra CFE",sector:"Energía",price:"$24.71",yield:"8.54%",occupancy:"—",dividend:"$2.10",tone:"gold",tags:["energia","infraestructura"]},
  TERRA:{ticker:"TERRA",name:"Terrafina",sector:"Industrial",price:"$1.20",yield:"—",occupancy:"95.8%",dividend:"$1.20",tone:"brown",tags:["industrial","logistica"]},
  FMX:{ticker:"FMX",name:"Fibra MX Infraestructura",sector:"Infraestructura",price:"$30.00",yield:"—",occupancy:"—",dividend:"$0.43",tone:"steel",tags:["infraestructura","energia"]},
};

const tabs: { id:Section; label:string; icon:typeof BarChart3 }[] = [
  { id:"resumen", label:"Resumen", icon:BarChart3 }, { id:"pagos", label:"Pagos", icon:CircleDollarSign }, { id:"valuacion", label:"Valuación", icon:PieChart }, { id:"ocupacion", label:"Ocupación", icon:WalletCards }, { id:"videos", label:"Videos", icon:Play }, { id:"reportes", label:"Reportes", icon:FileText },
];
const railLogos = ["IMG_2657_4549bbcb.PNG","IMG_2658_55c31b74.PNG","IMG_2659_a00a2856.PNG","IMG_2660_4bf28057.PNG","IMG_2661_649824a2.PNG","IMG_2662_751d91d2.PNG","IMG_2663_df8a0a91.PNG","IMG_2664_d1e7305c.PNG","IMG_2665_cc4aed41.PNG","IMG_2666_b5b4f952.PNG","IMG_2667_db59dfbe.PNG","IMG_2668_6f774556.PNG","IMG_2669_0228b243.PNG","IMG_2670_a4654862.PNG","IMG_2671_a8c356f6.PNG","IMG_2672_f5948ae8.PNG"];
const railTickers = ["FUNO","FIHO","FIBRAMQ","SOMA","FINN","FSHOP","DANHOS","FIBRAPL","FMTY","FNOVA","FPLUS","UPSITE","EDUCA","STORAGE","NEXT","FCFE"];
const logoByTicker: Record<string,string> = Object.fromEntries(railTickers.map((ticker,index) => [ticker, `/manus-storage/${railLogos[index]}`]));
const years = [2026, 2025, 2024, 2023, 2022];

export default function FibraDetail({ ticker, initialSection = "resumen" }: { ticker:string; initialSection?: Section }) {
  const fiber = data[ticker] ?? data.FUNO;
  const [active, setActive] = useState<Section>(initialSection);
  const [selectedVideo, setSelectedVideo] = useState<typeof previewVideos[number] | null>(null);
  const related = useMemo(() => getRelated(fiber), [fiber]);
  const fiberVideos = useMemo(() => { const key = `${fiber.ticker} ${fiber.name} ${fiber.sector} ${fiber.tags.join(" ")}`.toLowerCase(); const matched = previewVideos.filter(video => `${video.title} ${video.creator}`.toLowerCase().split(" ").some(term => term.length > 3 && key.includes(term))); return [...matched, ...previewVideos].filter((video, index, all) => all.findIndex(item => item.id === video.id) === index).slice(0, 8); }, [fiber]);
  const recommendationResult = selectedVideo ? getRecommendations(selectedVideo, previewVideos) : null;
  return <div className="mx-app">
    <header className="mx-header"><a href="/" className="mx-logo"><span />FIBRAS<span>.MX</span></a><nav className="mx-nav"><a className="mx-home-link" href="/">Inicio</a><a href="/fibras-mx"><BarChart3 size={14} />FIBRAs</a><a href="/fibras-mx/comparador">Comparador</a><a href="/fibras-mx/calculadora"><Calculator size={14} />Calculadora</a><a href="/fibras-mx/portafolio"><WalletCards size={14} />Portafolio</a></nav><div className="mx-market"><i /> BMV · México</div></header>
    <div className="mx-fiber-rail" aria-label="Explorar otras FIBRAs"><div className="mx-fiber-rail-track">{[...railTickers,...railTickers].map((symbol,index) => <a key={`${symbol}-${index}`} className="mx-rail-item" href={`/fibras-mx/fibra/${symbol}?seccion=videos`}><img src={`/manus-storage/${railLogos[index % railLogos.length]}`} alt={`Logotipo ${symbol}`} /><span>{symbol}</span></a>)}</div></div>
    <main className="mx-detail-main"><div className="mx-detail-actions"><a className="mx-back" href="/"><ArrowLeft size={14} /> Inicio editorial</a><a className="mx-back" href="/fibras-mx"><BarChart3 size={14} /> Catálogo FIBRAs</a></div>
      <section className="mx-detail-hero"><div className={`mx-detail-mark ${fiber.tone}`}>{fiber.ticker.slice(0,2)}</div><div><p className="mx-kicker">Ficha educativa · {fiber.sector}</p><h1>{fiber.ticker}</h1><p>{fiber.name}</p></div><div className="mx-detail-price"><span>Precio de referencia</span><strong>{fiber.price}</strong><small>MXN · valor observado</small></div></section>
      <nav className="mx-detail-tabs" aria-label="Secciones de la FIBRA">{tabs.map(({id,label,icon:Icon}) => <button key={id} className={active === id ? "active" : ""} onClick={() => setActive(id)}><Icon size={14} />{label}</button>)}</nav>
      <section className="mx-detail-content">
        {active === "resumen" && <><div className="mx-detail-grid"><Metric title="Yield orientativo" value={fiber.yield} note="Relación educativa entre distribución y precio." /><Metric title="Ocupación reportada" value={fiber.occupancy} note="Porcentaje de espacios ocupados como referencia." /><Metric title="Dividendo por certificado" value={`${fiber.dividend} MXN`} note="Dato de referencia anual; puede cambiar." /></div>{fiber.description && <ReferenceProfile fiber={fiber} />}<InfoBlock title="¿Qué estudia esta FIBRA?" icon={BookOpen}>Observa el sector, el tipo de inmueble y la forma en que genera ingresos. La ficha sirve para aprender a formular preguntas, no para indicar una compra.</InfoBlock></>}
        {active === "pagos" && <><InfoBlock title="Pagos y distribuciones" icon={CircleDollarSign}>Una FIBRA puede distribuir parte de sus ingresos a los tenedores de certificados. Revisa la periodicidad, el importe por certificado, las fechas relevantes y los documentos publicados antes de interpretar cualquier cifra.</InfoBlock><div className="mx-detail-grid"><Metric title="Referencia por certificado" value={`${fiber.dividend} MXN`} note="Valor educativo observado." /><Metric title="Periodicidad" value="Consultar" note="Debe confirmarse en el comunicado oficial." /><Metric title="Historial" value="Ver reportes" note="Consulta documentos oficiales." /></div></>}
        {active === "valuacion" && <><InfoBlock title="Valuación sin atajos" icon={PieChart}>La valuación compara precio, ingresos, ocupación, deuda, activos y distribución. Un yield alto por sí solo no determina si un instrumento es conveniente.</InfoBlock><div className="mx-detail-grid"><Metric title="Precio observado" value={fiber.price} note="No es precio objetivo." /><Metric title="Yield" value={fiber.yield} note="No es rendimiento garantizado." /><Metric title="Sector" value={fiber.sector} note="Ayuda a contextualizar riesgos." /></div></>}
        {active === "ocupacion" && <><InfoBlock title="Ocupación e inmuebles" icon={WalletCards}>La ocupación ayuda a entender cuánto espacio está rentado, pero debe leerse junto con concentración de inquilinos, vencimientos, rentas y calidad de los activos.</InfoBlock><div className="mx-occupancy-bar"><div><span>Ocupación de referencia</span><strong>{fiber.occupancy}</strong></div><div className="mx-bar"><i style={{width:fiber.occupancy === "—" ? "0%" : fiber.occupancy}} /></div><small>Indicador orientativo · verifica el reporte oficial</small></div></>}
        {active === "videos" && <FiberVideoLibrary fiber={fiber} videos={fiberVideos} selectedVideo={selectedVideo} recommendationResult={recommendationResult} onSelect={setSelectedVideo} />}
        {active === "reportes" && <ReportsSection ticker={fiber.ticker} />}
      </section>
      <RelatedFibers fibers={related} />
      <p className="mx-disclaimer">Información con fines educativos. Los datos pueden cambiar y deben verificarse en fuentes oficiales. Esta ficha no constituye asesoría financiera ni recomendación de compra o venta.</p>
    </main><footer className="mx-footer"><span>FIBRAS<span>.MX</span> — Centro educativo</span><span>Fuente de referencia · BMV / reportes oficiales</span></footer>
  </div>;
}

function getRelated(fiber: Fiber) { return Object.values(data).filter(item => item.ticker !== fiber.ticker).map(item => ({...item, score: (item.sector === fiber.sector ? 3 : 0) + item.tags.filter(tag => fiber.tags.includes(tag)).length})).sort((a,b) => b.score - a.score || a.ticker.localeCompare(b.ticker)).slice(0,3); }
function Metric({title,value,note}:{title:string;value:string;note:string}) { return <div className="mx-detail-metric"><span>{title}</span><strong>{value}</strong><small>{note}</small></div>; }
function ReferenceProfile({ fiber }: { fiber: Fiber }) { const metrics = [["Cambio", fiber.change], ["Cap. de mercado", fiber.marketCap], ["P/E", fiber.pe], ["Rango 52 semanas", fiber.annualRange], ["Valor en libros", fiber.bookValue], ["P/B", fiber.pb], ["Margen NOI", fiber.noiMargin], ["ROE", fiber.roe], ["Apalancamiento", fiber.leverage], ["Cobertura de deuda", fiber.debtCoverage], ["Propiedades", fiber.properties], ["Distribución anual", fiber.annualDividend], ["Frecuencia", fiber.frequency], ["Ingreso estimado", fiber.incomePer100k], ["ADR", fiber.adr], ["RevPAR", fiber.revpar], ["Margen EBITDA", fiber.ebitdaMargin]]; return <section className="mx-reference-profile"><div className="mx-reference-profile-heading"><div><p className="mx-kicker">Ficha ampliada · referencia educativa</p><h2>Datos para <em>estudiar.</em></h2></div><span>Actualización: {fiber.lastUpdated}</span></div><p className="mx-reference-description">{fiber.description}</p><div className="mx-reference-metrics">{metrics.filter(([, value]) => value).map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="mx-reference-profile-meta"><span>CEO: {fiber.ceo}</span><span>Fundada: {fiber.founded}</span><span>Empleados: {fiber.employees}</span><span>Sitio: {fiber.website}</span><small>Fuente: {fiber.source}</small></div></section>; }
function InfoBlock({title,icon:Icon,children}:{title:string;icon:typeof BookOpen;children:ReactNode}) { return <article className="mx-info-block"><Icon size={20} /><div><h2>{title}</h2><p>{children}</p></div></article>; }
function FiberVideoLibrary({ fiber, videos, selectedVideo, recommendationResult, onSelect }: { fiber: Fiber; videos: typeof previewVideos; selectedVideo: typeof previewVideos[number] | null; recommendationResult: ReturnType<typeof getRecommendations> | null; onSelect: (video: typeof previewVideos[number]) => void }) { return <section className="mx-fiber-videos" aria-label={`Videos educativos de ${fiber.name}`}><div className="mx-video-grid">{videos.map(video => <button className={`mx-video-card mx-video-card--interactive ${selectedVideo?.id === video.id ? "is-selected" : ""}`} type="button" key={video.id} onClick={() => onSelect(video)}><div className="mx-video-thumb"><img src={video.image} alt="" /><span className="mx-video-play"><Play size={16} fill="currentColor" /></span><small>{video.duration}</small></div><h3>{video.title}</h3><span>{video.creator} · {video.views}</span></button>)}</div>{selectedVideo && <div className="mx-video-detail"><div className="mx-video-detail-main"><div className="mx-video-detail-thumb"><img src={selectedVideo.image} alt="" /><span><Play size={24} fill="currentColor" /></span></div><div><p className="mx-kicker">Video seleccionado · {fiber.ticker}</p><h2>{selectedVideo.title}</h2><p>{selectedVideo.creator} · {selectedVideo.views}</p></div></div><div className="mx-fiber-recommendations"><h3>{recommendationResult?.title ?? "También puede interesarte"}</h3>{recommendationResult?.blocks.map(block => <section key={`${block.type}-${block.title}`}><h4>{block.title}</h4><div className="mx-fiber-recommendation-row">{block.videos.map(video => <button type="button" key={video.id} onClick={() => onSelect(video)}><img src={video.image} alt="" /><span><strong>{video.title}</strong><small>{video.creator} · {video.views}</small></span><em>{video.duration}</em></button>)}</div></section>)}</div></div>}</section>; }
function VideoCard({title,query}:{title:string;query:string}) { return <a className="mx-video-card" href={`https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`} target="_blank" rel="noreferrer"><div className="mx-video-thumb"><Play size={21} /></div><h3>{title}</h3><span>Buscar video educativo ↗</span></a>; }
function ReportsSection({ticker}:{ticker:string}) { const reports:Report[] = years.flatMap(year => [{year,period:"ANUAL",label:`Reporte anual ${year}`,status:"pending" as const},{year,period:"Q1",label:`Reporte trimestral Q1 ${year}`,status:"pending" as const},{year,period:"Q2",label:`Reporte trimestral Q2 ${year}`,status:"pending" as const},{year,period:"Q3",label:`Reporte trimestral Q3 ${year}`,status:"pending" as const},{year,period:"Q4",label:`Reporte trimestral Q4 ${year}`,status:"pending" as const}]); return <section className="mx-reports"><div className="mx-reports-heading"><div><p className="mx-kicker">Repositorio documental · {ticker}</p><h2>Reportes<br /><em>oficiales.</em></h2></div><p>Espacio preparado para cargar reportes anuales y trimestrales de los últimos cinco años, cuando existan y provengan de la fuente oficial.</p></div><div className="mx-report-notice"><FileText size={18} /><span>Los PDFs todavía no están cargados. Cada enlace se activará al añadir el documento correspondiente.</span></div><div className="mx-report-table">{reports.map(report => <div className="mx-report-row" key={`${report.year}-${report.period}`}><span>{report.year}</span><strong>{report.period}</strong><p>{report.label}</p>{report.url ? <a href={report.url} target="_blank" rel="noreferrer"><ExternalLink size={14} />Abrir PDF</a> : <small>Sin PDF cargado</small>}</div>)}</div></section>; }
function RelatedFibers({fibers}:{fibers: Fiber[]}) { return <section className="mx-related"><div className="mx-related-heading"><p className="mx-kicker">Lectura conectada</p><h2>FIBRAs<br /><em>relacionadas.</em></h2><p>Coincidencias educativas por sector y etiquetas de actividad. No es una recomendación de compra o venta.</p></div><div className="mx-related-grid">{fibers.map(fiber => <a className="mx-related-card" key={fiber.ticker} href={`/fibras-mx/fibra/${fiber.ticker}?seccion=videos`}><div className="mx-related-logo">{logoByTicker[fiber.ticker] ? <img src={logoByTicker[fiber.ticker]} alt={`Logotipo de ${fiber.name}`} /> : <span>{fiber.ticker.slice(0,2)}</span>}</div><div><strong>{fiber.ticker}</strong><span>{fiber.name}</span><small>{fiber.sector}</small></div><ArrowUpRight size={15} /></a>)}</div></section>; }
