/* Style reminder: /recursos is the secondary editorial hub — graphite canvas, crimson structure, neon-green tool signals, asymmetrical reading sections and restrained motion. */
import { ArrowUpRight, BookOpen, Calculator, Heart, MoveRight, Newspaper, WalletCards } from "lucide-react";
import { useEffect, useState } from "react";

const ebook = { title: "12 secretos para crecer orgánicamente", author: "Rubiel Valencia Heleria", description: "Una guía visual para aprender, crear contenido y construir una lectura constante del entorno digital.", cover: "/manus-storage/ebook-12-secretos-cover_79a33bb7.png", pdf: "/manus-storage/ebook_12_secretos_rubiel_valencia_edicion_visual_premium_0f921a8f.pdf" };
const amazonBook = { title: "Mi primera Fibra: Rentas sin propiedades", cover: "https://images-na.ssl-images-amazon.com/images/P/B0F7V748L8.01.LZZZZZZZ.jpg", url: "https://a.co/d/094djmIn" };
const news = [
  { number: "01", tag: "Guía de lectura", title: "Cómo leer un reporte trimestral de una FIBRA", copy: "Una ruta para ubicar ocupación, ingresos, deuda, distribución y notas importantes.", href: "/fibras-mx/fibra/FIHO?seccion=reportes" },
  { number: "02", tag: "Contexto", title: "Noticias del mercado inmobiliario para estudiar", copy: "Un espacio preparado para reunir artículos, comunicados y fuentes verificables.", href: "/recursos#noticias" },
  { number: "03", tag: "Fuentes", title: "Dónde consultar información oficial", copy: "Aprende a distinguir un dato observado de una interpretación educativa.", href: "/recursos#fuentes" },
];

export default function Home() {
  const [ebookOpen, setEbookOpen] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setEbookOpen(value => value === 0 ? 1 : 0), 9000); return () => window.clearInterval(timer); }, []);
  const active = ebookOpen === 0 ? ebook : amazonBook;
  return <div className="resources-page" id="inicio">
    <header className="resources-header"><a className="resources-brand" href="/"><span className="resources-brand-mark">F</span><span>FIBRAS<span className="resources-brand-red">.MX</span></span></a><nav className="resources-nav"><a href="#noticias">Noticias</a><a href="#lecturas">eBooks</a><a href="#herramientas">Herramientas</a><a href="/">Inicio editorial</a></nav></header>
    <main>
      <section className="resources-hero"><div className="resources-hero-copy"><p className="resources-kicker"><Newspaper size={14} /> Centro de noticias y recursos</p><h1>Leer el mercado.<br /><em>Entender el contexto.</em></h1><p>Noticias, libros y herramientas para estudiar las FIBRAs mexicanas con más claridad y menos ruido.</p><div className="resources-hero-actions"><a className="resources-primary" href="#noticias">Explorar noticias <MoveRight size={15} /></a><a className="resources-text-link" href="#lecturas">Ver eBooks <ArrowUpRight size={14} /></a></div></div><div className="resources-hero-note"><span>FIBRAS.MX / 02</span><strong>Lecturas<br /><em>adicionales.</em></strong><small>Un archivo en construcción para aprender a tu ritmo.</small></div></section>
      <section className="resources-news" id="noticias"><div className="resources-section-head"><div><p className="resources-kicker">01 / Noticias</p><h2>Información que<br /><em>merece contexto.</em></h2></div><p>La actualidad inmobiliaria se leerá aquí con una mirada educativa: fuente, fecha y explicación breve.</p></div><div className="resources-news-grid">{news.map(article => <a className="resources-news-card" href={article.href} key={article.number}><span className="resources-news-number">{article.number}</span><div><span className="resources-tag">{article.tag}</span><h3>{article.title}</h3><p>{article.copy}</p><b>Leer nota <ArrowUpRight size={14} /></b></div></a>)}</div></section>
      <section className="resources-readings" id="lecturas"><div className="resources-section-head"><div><p className="resources-kicker">02 / Lecturas adicionales</p><h2>Libros para<br /><em>seguir estudiando.</em></h2></div><p>Algunos recursos serán gratuitos; otros te llevarán a tus publicaciones disponibles en Amazon.</p></div><div className="resources-book-grid"><a className="resources-book-card resources-book-card--pdf" href={ebook.pdf} target="_blank" rel="noreferrer"><div className="resources-book-cover"><img src={ebook.cover} alt={`Portada de ${ebook.title}`} /></div><div><span className="resources-tag">PDF educativo</span><h3>{ebook.title}</h3><p>{ebook.description}</p><small>Por {ebook.author}</small><b>Abrir eBook <ArrowUpRight size={14} /></b></div></a><a className="resources-book-card resources-book-card--amazon" href={amazonBook.url} target="_blank" rel="noreferrer"><div className="resources-book-cover"><img src={amazonBook.cover} alt={`Portada de ${amazonBook.title}`} /></div><div><span className="resources-tag">Disponible en Amazon</span><h3>{amazonBook.title}</h3><p>Una introducción a las FIBRAs y a la idea de estudiar rentas inmobiliarias sin poseer directamente una propiedad.</p><small>Libro del creador</small><b>Ver en Amazon <ArrowUpRight size={14} /></b></div></a></div><div className="resources-book-rotation"><span>Rotación editorial</span><strong>{active.title}</strong><small>La promoción cambia de recurso cada pocos segundos.</small></div></section>
      <section className="resources-tools" id="herramientas"><div className="resources-section-head"><div><p className="resources-kicker">03 / Herramientas</p><h2>Aprende haciendo.</h2></div><p>Accesos rápidos para observar el mercado sin convertir una herramienta educativa en una orden de inversión.</p></div><div className="resources-tool-grid"><a className="resources-tool-link" href="/fibras-mx/calculadora"><span>Simulador</span><small>Escenarios hipotéticos</small><i /></a><a className="resources-tool-link" href="/fibras-mx/portafolio"><span>Portafolio</span><small>Seguimiento manual</small><i /></a><a className="resources-tool-link" href="/fibras-mx"><span>Catálogo FIBRAs</span><small>Exploración educativa</small><i /></a></div></section>
      <section className="resources-sources" id="fuentes"><div><p className="resources-kicker">04 / Biblioteca futura</p><h2>Una IA que<br /><em>aprende con fuentes.</em></h2></div><div><p>La futura burbuja de IA de FIBRAS.MX podrá responder preguntas basadas en artículos, tesis, revistas y reportes que incorporemos con fuente y fecha.</p><span className="resources-source-note">No responde todavía · módulo conceptual</span></div></section>
    </main><footer className="resources-footer"><a href="/">FIBRAS<span>.MX</span></a><span>Noticias · eBooks · herramientas educativas</span><a href="/">Volver al inicio editorial <ArrowUpRight size={13} /></a></footer>
  </div>;
}
